services:
  jobs-watcher:
    image: ghcr.io/vruzhentsov/jobs-watcher:${IMAGE_TAG:-latest}
    container_name: jobs-watcher-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - jobs-watcher-network

  redis:
    image: redis:7-alpine
    container_name: jobs-watcher-redis
    ports:
      - "6379:6379"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - jobs-watcher-network

  postgres:
    image: postgres:15-alpine
    container_name: jobs-watcher-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - jobs-watcher-network

volumes:
  postgres_data:

networks:
  jobs-watcher-network:
    driver: bridge
