[project]
name = "jobs-watcher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.20.0.post0",
    "flask>=3.0.0",
    "sentry-sdk[flask]>=2.29.1",
]
