name: Deploy to Remote Server

on:
  workflow_run:
    workflows: ["Publish Docker image"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Deploy to remote server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        # key: ${{ secrets.SERVER_SSH_KEY }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT || 22 }}
        script: |
          echo "=== Starting deployment ==="
          
          # Navigate to application directory in home folder
          cd ${{ secrets.APP_DIRECTORY || '~/' }}
          
          # Set image tag to latest
          export IMAGE_TAG="latest"
          echo "Deploying image tag: $IMAGE_TAG"          # Pull latest images
          echo "=== Pulling Docker images ==="
          docker compose pull jobs-watcher
          
          # Restart jobs-watcher service
          echo "=== Restarting jobs-watcher service ==="
          docker compose restart jobs-watcher
          
          # Wait for health check
          echo "=== Waiting for health check ==="
          sleep 30
          
          # Check if containers are running
          echo "=== Checking container status ==="
          docker-compose ps
          
          # Verify health endpoint
          echo "=== Verifying application health ==="
          curl -f http://localhost:5000/health || echo "Health check failed, but continuing..."
          
          echo "=== Deployment completed ==="

    - name: Notify deployment status
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "✅ Deployment completed successfully"
        else
          echo "❌ Deployment failed"
        fi
